apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qm3k5aksc-go 
  janus-idp.io/tekton: qm3k5aksc-go
  backstage.io/kubernetes-id: qm3k5aksc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qm3k5aksc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml