apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qm3k5aksc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qm3k5aksc-go 
  name: qm3k5aksc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qm3k5aksc-go 
